namespace XLib.Configs.Sheets.Types {

	public enum ConditionType {
		NUMBER_GREATER,
		NUMBER_GREATER_THAN_EQ,
		NUMBER_LESS,
		NUMBER_LESS_THAN_EQ,
		NUMBER_EQ,
		NUMBER_NOT_EQ,
		NUMBER_BETWEEN,
		NUMBER_NOT_BETWEEN,
		TEXT_CONTAINS,
		TEXT_NOT_CONTAINS,
		TEXT_STARTS_WITH,
		TEXT_EQ,
		TEXT_IS_EMAIL,
		TEXT_IS_URL,
		DATE_EQ,
		DATE_BEFORE,
		DATE_AFTER,
		DATE_ON_OR_BEFORE,
		DATE_ON_OR_AFTER,
		DATE_BETWEEN,
		DATE_NOT_BETWEEN,
		DATE_IS_VALID,
		ONE_OF_RANGE,
		ONE_OF_LIST,
		BLANK,
		NOT_BLANK,
		CUSTOM_FORMULA,
		BOOLEAN,
		TEXT_NOT_EQ,
		DATE_NOT_EQ
	}

}